### ISSUE TITLE
Build error ruby-opencv (0.0.14)

### ISSUE THREAD

**Issue by pietheinstrengholt** [feedbin/feedbin#171]
I tried to build feedbin using different versions of ruby (ruby-2.0.0-p648, ruby-2.3*, etc.). It fails with:

```
Installing ruby-opencv 0.0.14 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/local/rvm/rubies/ruby-2.0.0-p648/bin/ruby -r ./siteconf20160406-29885-1i0e5az.rb extconf.rb
>> Check the required libraries...
checking for main() in -lstdc++... yes
checking for main() in -lopencv_calib3d... yes
checking for main() in -lopencv_contrib... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/rvm/rubies/ruby-2.0.0-p648/bin/ruby
        --with-opencv-dir
        --without-opencv-dir
        --with-opencv-include
        --without-opencv-include=${opencv-dir}/include
        --with-opencv-lib
        --without-opencv-lib=${opencv-dir}/lib
        --with-libxml2-dir
        --without-libxml2-dir
        --with-libxml2-include
        --without-libxml2-include=${libxml2-dir}/include
        --with-libxml2-lib
        --without-libxml2-lib=${libxml2-dir}/lib
        --with-stdc++lib
        --without-stdc++lib
        --with-opencv_calib3dlib
        --without-opencv_calib3dlib
        --with-opencv_contriblib
        --without-opencv_contriblib
extconf.rb:58:in `block in <main>': opencv_contrib not found. (RuntimeError)
        from extconf.rb:58:in `each'
        from extconf.rb:58:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.0.0-p648/gems/ruby-opencv-0.0.14 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.0.0-p648/extensions/x86_64-linux/2.0.0/ruby-opencv-0.0.14/gem_make.out
```

Any clue how to fix this?

**Comment by pietheinstrengholt** [comment]
I tried setting up feedbin without opencv (by commenting it out in the Gemfile), but I then get the following error:

`20:29:37 worker_slow.1 | /home/feedbin/.gems/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require': No such file to load -- opencv (LoadError)`

This happens on different platforms (ubuntu and synology system). I guess opencv is really needed.

**Comment by benubois** [comment]
Image processing won't work without it, but that's about it. If you're determined to not use it you can also comment out any instance of require 'opencv'

It is not difficult to install opencv though. You're probably missing dependencies. Try googling "install opencv YOUR_PLATFORM"

Thanks!

**Comment by benubois** [comment]
opencv is no longer a dependency.
