### ISSUE TITLE
FeedRefresher fails: undefined method `<' for nil:NilClass

### ISSUE THREAD

**Issue by fnkr** [feedbin/feedbin#175]
Feed refreshing does not work and I get tons of this error:

```
10:46:41 worker_slow.1 | 2016-04-24T10:46:41.741Z 159 TID-k7w10 FeedRefresher JID-627d34946c77b44e67c450b8 INFO: fail: 0.065 sec
10:46:41 worker_slow.1 | 2016-04-24T10:46:41.741Z 159 TID-k7w10 WARN: {"args"=>[1, false], "class"=>"FeedRefresher", "queue"=>"worker_slow_critical", "retry"=>true, "jid"=>"627d34946c77b44e67c450b8", "created_at"=>1461494023.0055375, "enqueued_at"=>1461494801.650708, "error_message"=>"undefined method `<' for nil:NilClass", "error_class"=>"NoMethodError", "failed_at"=>1461494023.068091, "retry_count"=>5, "retried_at"=>1461494801.7392123}
10:46:41 worker_slow.1 | 2016-04-24T10:46:41.741Z 159 TID-k7w10 WARN: NoMethodError: undefined method `<' for nil:NilClass
10:46:41 worker_slow.1 | 2016-04-24T10:46:41.741Z 159 TID-k7w10 WARN: /home/feedbin/feedbin/app/workers/feed_refresher.rb:87:in `push?'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/app/workers/feed_refresher.rb:75:in `push_callback'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/app/workers/feed_refresher.rb:65:in `to_a'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/app/workers/feed_refresher.rb:26:in `block in build_arguments'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/app/workers/feed_refresher.rb:23:in `each'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/app/workers/feed_refresher.rb:23:in `each_with_object'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/app/workers/feed_refresher.rb:23:in `build_arguments'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/app/workers/feed_refresher.rb:12:in `perform'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:151:in `execute_job'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:133:in `block (2 levels) in process'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/app/models/worker_stat.rb:7:in `block in call'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/librato-rack-0.6.0/lib/librato/collector/aggregator.rb:80:in `measure'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/app/models/worker_stat.rb:6:in `call'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/logging.rb:31:in `with_context'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:132:in `call'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:128:in `block in process'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:167:in `stats'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:127:in `process'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:79:in `process_one'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:67:in `run'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:16:in `watchdog'
10:46:41 worker_slow.1 | /home/feedbin/feedbin/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

Cause: https://github.com/feedbin/feedbin/blob/e844a8961d0762617934c15199a54e3506c768ff/app/workers/feed_refresher.rb#L87
`@feed[:push_expiration]` seems to be nil or so? I modified the line like this and it works now:

```
@push ||= @push_url && @feed[:push_expiration].nil? || !@feed[:push_expiration].nil? && @feed[:push_expiration] < Time.now
```

**Comment by dfyx** [comment]
I can see the same problem on my instance running the `scavone/feedbin` and `scavone/feedbin-refresher` docker containers.

**Comment by dfyx** [comment]
Update: I guess you can also fix this by just setting the `PUSH_URL` environment variable to the root url of your instance.

**Comment by fnkr** [comment]
Here is my Dockerfile: [fnkr/feedbin-docker](https://github.com/fnkr/docker-feedbin).
