### ISSUE TITLE
sidekiq > 4.1.1 breaks feedbin - refresher interface

### ISSUE THREAD

**Issue by bkero** [feedbin/feedbin#177]
The latest feedbin release (61c120b8fa956338269917de1c7737f7868e1939) updates many dependencies. One of the dependencies that was updated was sidekiq, from 4.1.1 to 4.1.2. Upgrading gems to this version and attempting to run feedbin/refresher yields a never-ending stream of refresher errors.

```
16:06:05 worker_slow.1 | 2016-05-20T16:06:05.144Z 21240 TID-zc9tk FeedRefresher JID-79394f3c9271cb5b4b74163e INFO: fail: 0.179 sec
16:06:05 worker_slow.1 | 2016-05-20T16:06:05.144Z 21240 TID-zc9tk WARN: {"args":[1,true],"class":"FeedRefresher","queue":"worker_slow_critical","retry":true,"jid":"79394f3c9271cb5b4b74163e","created_at":1463759893.0315154,"enqueued_at":1463760364.798314,"error_message":"Bulk arguments must be an Array of Arrays: [[1], [2]]","error_class":"ArgumentError","failed_at":1463759893.2095885,"retry_count":2,"retried_at":1463760365.141155}
16:06:05 worker_slow.1 | 2016-05-20T16:06:05.144Z 21240 TID-zc9tk WARN: ArgumentError: Bulk arguments must be an Array of Arrays: [[1], [2]]
16:06:05 worker_slow.1 | 2016-05-20T16:06:05.144Z 21240 TID-zc9tk WARN: /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/client.rb:87:in `push_bulk'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/client.rb:129:in `push_bulk'
16:06:05 worker_slow.1 | /home/ubuntu/feedbin/app/workers/feed_refresher.rb:11:in `perform'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:152:in `execute_job'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:134:in `block (2 levels) in process'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
16:06:05 worker_slow.1 | /home/ubuntu/feedbin/app/models/worker_stat.rb:7:in `block in call'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/librato-rack-1.0.0/lib/librato/collector/aggregator.rb:80:in `measure'
16:06:05 worker_slow.1 | /home/ubuntu/feedbin/app/models/worker_stat.rb:6:in `call'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/honeybadger-2.6.0/lib/honeybadger/plugins/sidekiq.rb:12:in `block in call'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/honeybadger-2.6.0/lib/honeybadger/trace.rb:87:in `instrument'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/honeybadger-2.6.0/lib/honeybadger/trace.rb:20:in `instrument'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/honeybadger-2.6.0/lib/honeybadger/plugins/sidekiq.rb:11:in `call'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/logging.rb:32:in `with_context'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/logging.rb:7:in `call'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:133:in `invoke'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:129:in `block in process'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:168:in `stats'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:128:in `process'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:80:in `process_one'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:68:in `run'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/util.rb:17:in `watchdog'
16:06:05 worker_slow.1 | /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/util.rb:25:in `block in safe_thread'

```

**Comment by benubois** [comment]
Hi @bkero,

Thanks for reporting this! Any interest in following the stack trace to see where the problem is or what has changed?

Thanks,

Ben
