### ISSUE TITLE
Can't run without a Stripe account

### ISSUE THREAD

**Issue by brendanlong** [feedbin/feedbin#229]
If you don't have a STRIPE_API_KEY set:

```
$ rake db:setup
Stripe::AuthenticationError: No API key provided. Set your API key using "Stripe.api_key = <API-KEY>". You can generate API keys from the Stripe web interface. See https://stripe.com/api for details, or email support@stripe.com if you have any questions.
/usr/local/share/gems/gems/stripe-3.3.1/lib/stripe/stripe_client.rb:177:in `check_api_key!'
/usr/local/share/gems/gems/stripe-3.3.1/lib/stripe/stripe_client.rb:118:in `execute_request'
/usr/local/share/gems/gems/stripe-3.3.1/lib/stripe/api_operations/request.rb:19:in `request'
/usr/local/share/gems/gems/stripe-3.3.1/lib/stripe/api_operations/create.rb:5:in `create'
/feedbin/app/models/customer.rb:8:in `create'
/feedbin/app/models/user.rb:252:in `create_customer'
/feedbin/app/models/user.rb:74:in `block in <class:User>'
```

I was able to fix this but it was super annoying:
 1. Create a Stripe account
 2. Manually a test plan named `trial`
 3. Setup `STRIPE_API_KEY` and `STRIPE_PUBLIC_KEY`

**Comment by wasmitnetzen** [comment]
I investigated this a little bit to find another workaround. The reason for this is that `app/models/customer.rb ` is a wrapper around the Stripe class, which is called from ` feedbin/app/models/user.rb` on account creation. This is called in [user.rb#74](https://github.com/feedbin/feedbin/blob/f095790b2cf2570fb5c640936be8bf6e89762577/app/models/user.rb#L74). If you comment that line, account creation works again without having a Stripe key.

**Comment by brendanlong** [comment]
I wonder if we could wrap that line with `if :stripe_token` or something..

**Comment by wasmitnetzen** [comment]
Sure, something like
```
if ENV["STRIPE_API_KEY"] && ENV["STRIPE_PUBLIC_KEY"] 
  before_create { create_customer }
```
should also work.
