### ISSUE TITLE
Assers 'website-icon.svg' not found in master

### ISSUE THREAD

**Issue by thomas-illiet** [feedbin/feedbin#284]
Hello Guys :)

Today i run master branch in my server and  i have this error :

```shell
I, [2018-10-15T18:31:11.994037 #23]  INFO -- : method=GET path=/ format=html controller=SiteController action=index status=302 duration=7.89 view=0.00 db=0.93 location=http://172.16.5.201:9292/login
I, [2018-10-15T18:31:12.031245 #23]  INFO -- : method=GET path=/login format=html controller=SessionsController action=new status=500 error='ActionView::Template::Error: The asset "website-icon.svg" is not present in the asset pipeline.' duration=10.01 view=0.00 db=0.64
F, [2018-10-15T18:31:12.033238 #23] FATAL -- :
F, [2018-10-15T18:31:12.033338 #23] FATAL -- : ActionView::Template::Error (The asset "website-icon.svg" is not present in the asset pipeline.):
F, [2018-10-15T18:31:12.033652 #23] FATAL -- :      5:         <meta name="viewport" content="initial-scale=1.0,width=device-width,user-scalable=no,viewport-fit=cover" />
     6:         <meta name="apple-mobile-web-app-capable" content="yes">
     7:         <meta name="apple-mobile-web-app-status-bar-style" content="default">
     8:         <link rel="mask-icon" href="<%= asset_path('website-icon.svg') %>" color="#000000" />
     9:         <link rel="icon" href="<%= asset_path('link-icon.png') %>" sizes="192x192" />
    10:         <link rel="apple-touch-icon-precomposed" href="<%= asset_path('apple-touch-icon-precomposed.png') %>" sizes="152x152" />
    11:         <link rel="shortcut icon" href="<%= asset_path('favicon.ico') %>" type="image/vnd.microsoft.icon" />
F, [2018-10-15T18:31:12.033721 #23] FATAL -- :
F, [2018-10-15T18:31:12.033772 #23] FATAL -- : app/views/layouts/application.html.erb:8:in `_app_views_layouts_application_html_erb__3612758159123793538_47003855009820'
lib/basic_authentication.rb:10:in `call'
E, [2018-10-15T18:31:12.041768 #23] ERROR -- : ** [Honeybadger] Unable to send error report: API key is missing. id=f52a50a4-e662-411f-b608-e38fea6ea20d level=3 pid=23
F, [2018-10-15T18:31:12.305609 #23] FATAL -- :
F, [2018-10-15T18:31:12.305741 #23] FATAL -- : ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
F, [2018-10-15T18:31:12.305798 #23] FATAL -- :
F, [2018-10-15T18:31:12.305867 #23] FATAL -- : actionpack (5.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
lograge (0.10.0) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
railties (5.1.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
honeybadger (4.0.0) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
honeybadger (4.0.0) lib/honeybadger/agent.rb:345:in `with_rack_env'
honeybadger (4.0.0) lib/honeybadger/rack/error_notifier.rb:30:in `call'
honeybadger (4.0.0) lib/honeybadger/rack/user_feedback.rb:31:in `call'
honeybadger (4.0.0) lib/honeybadger/rack/user_informer.rb:21:in `call'
railties (5.1.6) lib/rails/engine.rb:522:in `call'
railties (5.1.6) lib/rails/railtie.rb:185:in `public_send'
railties (5.1.6) lib/rails/railtie.rb:185:in `method_missing'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
I, [2018-10-15T18:31:12.308856 #23]  INFO -- : method=GET path=/404 format=html controller=ErrorsController action=not_found status=404 duration=1.63 view=0.16 db=0.17
E, [2018-10-15T18:31:12.309278 #23] ERROR -- : ** [Honeybadger] Unable to send error report: API key is missing. id=24a0edc7-31fe-4ba3-896b-53c514183c67 level=3 pid=23

```

https://github.com/feedbin/feedbin/blob/533be9d1b954a3e2a560910061e5d830ce6cb82e/app/views/layouts/application.html.erb#L8

Do you have any idea for this problem?

**Comment by angristan** [comment]
If anyone is having this issue: you need to run `bundle exec rake assets:precompile`.
