### ISSUE TITLE
Requests involving templates that contain assets fail

### ISSUE THREAD

**Issue by pierre-le** [feedbin/feedbin#300]
### Issue

I've just set up a new Docker container to deploy FeedBin. Everything works out just fine, except when I try to load a page (which would be the login page apparently), in which case I get this error:

```
feedbin-app              | I, [2019-01-29T18:36:02.588657 #11]  INFO -- : method=GET path=/login format=html controller=SessionsController action=new status=500 error='ActionView::Template::Error: The asset "website-icon.svg" is not present in the asset pipeline.' duration=55.69 view=0.00 db=13.82
feedbin-app              | F, [2019-01-29T18:36:02.589663 #11] FATAL -- :
feedbin-app              | F, [2019-01-29T18:36:02.589719 #11] FATAL -- : ActionView::Template::Error (The asset "website-icon.svg" is not present in the asset pipeline.):
feedbin-app              | F, [2019-01-29T18:36:02.589897 #11] FATAL -- :     19:                 }
feedbin-app              |     20:             }
feedbin-app              |     21:         </script>
feedbin-app              |     22:         <link rel="mask-icon" href="<%= asset_path('website-icon.svg') %>" color="#000000" />
feedbin-app              |     23:         <link rel="icon" href="<%= asset_path('link-icon.png') %>" sizes="192x192" />
feedbin-app              |     24:         <link rel="apple-touch-icon-precomposed" href="<%= asset_path('apple-touch-icon-precomposed.png') %>" sizes="152x152" />
feedbin-app              |     25:         <link rel="shortcut icon" href="<%= asset_path('favicon.ico') %>" type="image/vnd.microsoft.icon" />
feedbin-app              | F, [2019-01-29T18:36:02.589953 #11] FATAL -- :
feedbin-app              | F, [2019-01-29T18:36:02.589995 #11] FATAL -- : app/views/layouts/application.html.erb:22:in `_app_views_layouts_application_html_erb__3115092446635195341_47137455252560'
feedbin-app              | lib/tld_length.rb:13:in `call'
feedbin-app              | lib/basic_authentication.rb:10:in `call'
feedbin-app              | E, [2019-01-29T18:36:02.601846 #11] ERROR -- : ** [Honeybadger] Unable to send error report: API key is missing. id=f004a854-d220-47aa-847c-d90f06bd8cf9 level=3 pid=11
```

This error seems to relate to [another issue](https://github.com/feedbin/feedbin/issues/284), that was closed by its author (so I guess he sorted it out somehow).

Is there something I've missed out?

### Steps to reproduce

1. Setup a new FeedBin instance, by following the docs.
2. Try to access the app.

**Comment by benubois** [comment]
Hi @pierre-le, 

Unfortunately I cannot provide support for self-hosting Feedbin. There's a [fork of Feedbin](https://github.com/rach-sharp/freedbin) that uses Docker. I haven't used it but it seems to be high-quality. Maybe give that a try?

**Comment by angristan** [comment]
If anyone is having this issue: you need to run `bundle exec rake assets:precompile`.
