### ISSUE TITLE
rake db:setup Error

### ISSUE THREAD

**Issue by mzch** [feedbin/feedbin#310]
I tried to install feedbin on Debian 9 Stretch. But rake db:setup failed. Any idea?

OS: Debian 9 Stretch (9.6)
ruby: 2.6.1
rake: rake, version 12.3.2

```
$ sudo -u feedbin rake db:setup
/srv/feedbin/app/models/entry.rb:96: syntax error, unexpected keyword_rescue, expecting keyword_end
/srv/feedbin/app/models/entry.rb:424: syntax error, unexpected end-of-input, expecting keyword_end
rake aborted!
SyntaxError: /srv/feedbin/app/models/entry.rb:96: syntax error, unexpected keyword_rescue, expecting keyword_end
/srv/feedbin/app/models/entry.rb:424: syntax error, unexpected end-of-input, expecting keyword_end
/var/lib/gems/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/var/lib/gems/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:477:in `block in load_file'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:662:in `new_constants_in'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:476:in `load_file'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:374:in `block in require_or_load'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:36:in `block in load_interlock'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies/interlock.rb:11:in `loading'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:36:in `load_interlock'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:357:in `require_or_load'
/var/lib/gems/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `block in require_or_load'
/var/lib/gems/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
/var/lib/gems/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:47:in `require_or_load'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:511:in `load_missing_constant'
/var/lib/gems/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant'
/var/lib/gems/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
/var/lib/gems/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:202:in `const_missing'
/srv/feedbin/config/initializers/elasticsearch.rb:17:in `<main>'
/var/lib/gems/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/var/lib/gems/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:286:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:286:in `load'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/engine.rb:655:in `block in load_config_initializer'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/notifications.rb:168:in `instrument'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/engine.rb:654:in `load_config_initializer'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/engine.rb:611:in `each'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/engine.rb:611:in `block in <class:Engine>'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:59:in `block in run_initializers'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:48:in `each'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:48:in `tsort_each_child'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:58:in `run_initializers'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/application.rb:353:in `initialize!'
/srv/feedbin/config/environment.rb:5:in `<main>'
/var/lib/gems/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/var/lib/gems/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/var/lib/gems/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
/var/lib/gems/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/var/lib/gems/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
/srv/feedbin/lib/tasks/feedbin_generate_coupon.rake:2:in `<main>'
/var/lib/gems/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/var/lib/gems/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:286:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:286:in `load'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/engine.rb:648:in `block in run_tasks_blocks'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/engine.rb:648:in `each'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/engine.rb:648:in `run_tasks_blocks'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/application.rb:440:in `run_tasks_blocks'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/engine.rb:457:in `load_tasks'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/railtie.rb:185:in `public_send'
/var/lib/gems/2.3.0/gems/railties-5.1.6.2/lib/rails/railtie.rb:185:in `method_missing'
/srv/feedbin/Rakefile:6:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by benubois** [comment]
Are you sure you are running this on Ruby 2.6?

That line number is a rescue inside a block. Support for this was added in ruby 2.5, but earlier versions would probably throw an exception like you’re seeing.

**Comment by mzch** [comment]
Oh, my server has a system default ruby! Thanks!
