### ISSUE TITLE
500 on GET /extracts/:id/entry

### ISSUE THREAD

**Issue by angristan** [feedbin/feedbin#435]
Hello!

When clicking on "Extract full content" the XHR request is answered with an empty 500 on my Feedbin installation. [Another user has also this issue](https://github.com/angristan/feedbin-docker/issues/6).

This is the server-side trace:

```
feedbin-web_1            | I, [2020-03-29T16:40:46.824871 #1]  INFO -- : method=GET path=/extracts/7914/entry format=js controller=ExtractsController action=entry status=500 error='NoMethodError: undefined method `check_for_image' for #<ExtractsController:0x00007f1e283a7e18>' duration=207.92 view=0.00 db=19.65
feedbin-web_1            | F, [2020-03-29T16:40:46.854732 #1] FATAL -- :
feedbin-web_1            | NoMethodError (undefined method `check_for_image' for #<ExtractsController:0x00007f1e283a7e18>):
feedbin-web_1            |
feedbin-web_1            | app/controllers/extracts_controller.rb:18:in `rescue in entry'
feedbin-web_1            | app/controllers/extracts_controller.rb:9:in `entry'
feedbin-web_1            | lib/tld_length.rb:13:in `call'
feedbin-web_1            | lib/basic_authentication.rb:10:in `call'
``` 

I'm running `master`. I assume this is working fine on feedbin.com. Could you give us pointers as to what could cause this issue?

Thanks a lot!

**Comment by benubois** [comment]
Do you have extract running locally? https://github.com/feedbin/extract

If not this is probably a side effect of not being able to call `MercuryParser.parse`.

To get extract working with Feedbin you need to add these environment variables to your installation: EXTRACT_HOST, EXTRACT_USER and EXTRACT_SECRET.

**Comment by angristan** [comment]
Oh! No this the first time I see extract. It was not documented anywhere 😅

We'll setup that service, thanks 👍

**Comment by angristan** [comment]
Hey @benubois, I've successfully set up extract 👍 

As you can see it works great here:

```
root@hitomi ~/feedbin-docker# docker-compose exec feedbin-web bash
root@a410aa567901:/app# curl -Ss feedbin-extract:3000/parser/username/e4696f8630bb68c21d77a9629ce8d063d8e5f81c?base64_url=aHR0cHM6Ly9mZWVkYmluLmNvbS9ibG9nLzIwMTgvMDkvMTEvcHJpdmF0ZS1ieS1kZWZhdWx0Lw== | jq '.title,.excerpt'
"Private by Default"
"September 11, 2018 by Ben Ubois I want Feedbin to be the opposite of Big Social. I think people should have the right not to be tracked on the Internet and Feedbin can help facilitate that. Since&hellip;"
```

However I still get this error:

```
feedbin-web_1            | I, [2020-03-31T12:57:35.782545 #1]  INFO -- : method=GET path=/extracts/8141/entry format=js controller=ExtractsController action=entry status=500 error='NoMethodError: undefined method `check_for_image' for #<ExtractsController:0x0000559ba4db0200>' duration=74.56 view=0.00 db=7.94
feedbin-web_1            | F, [2020-03-31T12:57:35.804563 #1] FATAL -- :
feedbin-web_1            | NoMethodError (undefined method `check_for_image' for #<ExtractsController:0x0000559ba4db0200>):
feedbin-web_1            |
feedbin-web_1            | app/controllers/extracts_controller.rb:18:in `rescue in entry'
feedbin-web_1            | app/controllers/extracts_controller.rb:9:in `entry'
feedbin-web_1            | lib/tld_length.rb:13:in `call'
feedbin-web_1            | lib/basic_authentication.rb:10:in `call'
```

I've setup the 3 env variables. Anything else I should be looking at?

**Comment by benubois** [comment]
Try removing the `rescue` blocks so you can get a backtrace to where the original exception is raised.

**Comment by angristan** [comment]
(Oops the issue closed itself, I can't reopen)

```
I, [2020-04-05T09:47:26.602997 #164]  INFO -- : method=GET path=/extracts/8579/entry format=js controller=ExtractsController action=entry status=500 error='URI::InvalidComponentError: bad component(expected host component): [feedbin-extract:3000]' duration=20.91 view=0.00 db=10.83
F, [2020-04-05T09:47:26.608907 #164] FATAL -- :
URI::InvalidComponentError (bad component(expected host component): [feedbin-extract:3000]):

app/models/mercury_parser.rb:55:in `service_url'
app/models/mercury_parser.rb:67:in `result'
app/models/mercury_parser.rb:20:in `content'
app/controllers/extracts_controller.rb:13:in `entry'
lib/tld_length.rb:13:in `call'
lib/basic_authentication.rb:10:in `call'
```

Looks like it does not support specifying a port?

https://github.com/feedbin/feedbin/blob/5aa9253626f58a5eb68db5f8f521727d432f6cbf/app/models/mercury_parser.rb#L55-L58

**Comment by angristan** [comment]
Well, ok, it only supports HTTPS over port 443. I'll add extract behing my reverse proxy :) Thanks for the help
