### ISSUE TITLE
rake aborted! ArgumentError: invalid uri scheme ''

### ISSUE THREAD

**Issue by sevospl** [feedbin/feedbin#640]
OS: FreeBSD 12.2-RELEASE-p5
Ruby version: ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-freebsd12.2]
Not using Docker (FreeBSD doesn't even support it)
All gems installed with bundle properly

When trying to run either `bundle exec rake` or `rake db:setup` I get following error (with trace):

```rake aborted!
ArgumentError: invalid uri scheme ''
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/redis-4.2.5/lib/redis/client.rb:441:in `_parse_options'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/redis-4.2.5/lib/redis/client.rb:89:in `initialize'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/redis-4.2.5/lib/redis.rb:62:in `new'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/redis-4.2.5/lib/redis.rb:62:in `initialize'
/usr/home/myuser/domains/mydomain.tld/public_ruby/config/initializers/rack_attack.rb:3:in `new'
/usr/home/myuser/domains/mydomain.tld/public_ruby/config/initializers/rack_attack.rb:3:in `<main>'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:326:in `block in load'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:326:in `load'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/engine.rb:681:in `block in load_config_initializer'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:205:in `instrument'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/engine.rb:680:in `load_config_initializer'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/engine.rb:633:in `each'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/engine.rb:633:in `block in <class:Engine>'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `instance_exec'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `run'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/home/myuser/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
/usr/home/myuser/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/home/myuser/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/home/myuser/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/home/myuser/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/initializable.rb:50:in `each'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/home/myuser/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:415:in `call'
/usr/home/myuser/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/home/myuser/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/home/myuser/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:347:in `each'
/usr/home/myuser/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:347:in `call'
/usr/home/myuser/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/home/myuser/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
/usr/home/myuser/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/initializable.rb:60:in `run_initializers'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/application.rb:384:in `initialize!'
/usr/home/myuser/domains/mydomain.tld/public_ruby/config/environment.rb:5:in `<main>'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `block in require'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `require'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
/usr/home/myuser/domains/mydomain.tld/public_ruby/lib/tasks/feedbin_generate_coupon.rake:2:in `<main>'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:326:in `block in load'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:326:in `load'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/engine.rb:675:in `block in run_tasks_blocks'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/engine.rb:675:in `each'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/engine.rb:675:in `run_tasks_blocks'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/application.rb:521:in `run_tasks_blocks'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/engine.rb:464:in `load_tasks'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/railtie.rb:207:in `public_send'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/railties-6.1.3.1/lib/rails/railtie.rb:207:in `method_missing'
/usr/home/myuser/domains/mydomain.tld/public_ruby/Rakefile:6:in `<top (required)>'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/rake-13.0.3/lib/rake/rake_module.rb:29:in `load'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/rake-13.0.3/lib/rake/rake_module.rb:29:in `load_rakefile'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/rake-13.0.3/lib/rake/application.rb:703:in `raw_load_rakefile'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/rake-13.0.3/lib/rake/application.rb:104:in `block in load_rakefile'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/rake-13.0.3/lib/rake/application.rb:103:in `load_rakefile'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/rake-13.0.3/lib/rake/application.rb:82:in `block in run'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/bin/rake:23:in `load'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/bin/rake:23:in `<main>'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/bin/ruby_executable_hooks:22:in `eval'
/usr/home/myuser/.rvm/gems/ruby-2.7.3/bin/ruby_executable_hooks:22:in `<main>'
```
And that's despite from having environment variables (`.env`) set properly, including PostgreSQL and Redis.

I'm not really familiar with Ruby as whole so if anyone could point me in the right direction to solve the issue I would greatly appreciate this. Thanks.

BTW: I also tried Ruby 2.6 which was suggested in the docs.

**Comment by nanaya** [comment]
You need to specify all three `REDIS_*` env variable.

**Comment by w3villa-ankit** [comment]
any solution?

**Comment by Avamander** [comment]
Why the hell does `bundle exec rake assets:precompile` run `feedbin_generate_coupon.rake` and expect a working ElasticSearch?
